common: &common
  adapter: mysql2
  host: localhost
  username: root 
  password: root1114
  encoding: utf8
  pool: 5
  reconnect: false
  socket: /tmp/mysql.sock

development: &development
  <<: *common
  database: camobyte_dev
  
test: &TEST
  <<: *common
  database: camobyte_test

production:
  <<: *common
  database: camobyte_production

cucumber:
  <<: *TEST

js_development:
  <<: *development
